# Definición de etapas
stages:
  - test

# Pruebas de Cypress
cypress-test-job:
  stage: test
  image: cypress/browsers
  script:
    - npm ci
    - echo "Ejecutando pruebas de cypress..."
    - npx cypress run

  artifacts:
    paths:
      - cypress/
    when: always

